version: '3'
services:
    node-instabot-liker:
        container_name: node-instabot-liker
        build: ./node-instabot-liker
        environment:
          DB_HOST: "mongodb://mongo:27017"
          DB_NAME: "instabot"
          INSTABOT_SCRAPP_USER: "leo_dls_"
          INSTABOT_SCRAPP_PASS: "Kjkszpj$$@5"
          LIKE_MAX_MINUTES: 15
          LIKE_MIN_MINUTES: 10
          DAILY_LIKE: 1400
          LIKE_DELAY_MAX: 10000
          LIKE_DELAY_MIN: 5000
        command: make run
        restart: always
        volumes:
          - ./node-instabot-liker/src:/app/src
        links:
          - mongo
    node-instabot-scrapper:
        container_name: node-instabot-scrapper
        build: ./node-instabot-scrapper
        environment:
          DB_HOST: "mongodb://mongo:27017"
          DB_NAME: "instabot"
          INSTABOT_SCRAPP_USER: "leopold_testing"
          INSTABOT_SCRAPP_PASS: "Kjkszpj$$5"
        command: make run
        restart: always
        volumes:
          - ./node-instabot-scrapper/src:/app/src
        links:
          - mongo
    node-instabot-logger:
        container_name: node-instabot-logger
        build: ./node-instabot-logger
        environment:
          DB_HOST: "mongodb://mongo:27017"
          DB_NAME: "instabot"
        command: make run
        restart: always
        volumes:
          - ./node-instabot-logger/src:/app/src
        links:
          - mongo
    node-instabot-mongo:
        container_name: node-instabot-mongo
        build: ./node-instabot-mongo
        environment:
          DB_HOST: "mongodb://mongo:27017"
          DB_NAME: "instabot"
        command: make run
        restart: always
        volumes:
          - ./node-instabot-mongo/src:/app/src
        links:
          - mongo
    mongo:
        container_name: mongo
        image: mongo
        ports:
            - "27017:27017"
